server:
  port: 8005

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: service-takeout
  datasource:
    url: jdbc:mysql://192.168.110.162:3306/heikeji_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql@8Root!2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
  autoconfigure:
    exclude:
      - io.github.resilience4j.autoconfigure.Resilience4jAutoConfiguration
      - io.github.resilience4j.autoconfigure.CircuitBreakerAutoConfiguration
      - io.github.resilience4j.autoconfigure.CircuitBreakerConfigurationOnMissingBean
      - io.github.resilience4j.autoconfigure.RetryAutoConfiguration
      - io.github.resilience4j.autoconfigure.RateLimiterAutoConfiguration


mybatis-plus:
  mapper-locations: classpath*:com/heikeji/mall/takeout/mapper/*.xml
  type-aliases-package: com.heikeji.mall.takeout.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    validation-mode: NONE

# 文件上传配置
file:
  upload:
    path: ./upload/images
    # 外部访问路径
    access-path: /upload/images/**

logging:
  level:
    root: info
    com.heikeji.mall.takeout: debug